export const mockContractsResponse = {
  data: {
    contracts: [
      {
        id: 4596,
        code: 'F0839624 ',
        name: 'Возвраты неотгруженные',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '2012-08-23T00:00:00Z',
        isDeleted: false,
        isGoods: true,
      },
      {
        id: 4877,
        code: 'F0839625 ',
        name: 'Возвраты отгруженные',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '0001-01-01T00:00:00Z',
        isDeleted: false,
        isGoods: true,
      },
      {
        id: 9577,
        code: 'F0839622 ',
        name: 'Закрытые поставки',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '0001-01-01T00:00:00Z',
        isDeleted: false,
        isGoods: true,
      },
      {
        id: 13163,
        code: 'F0839623 ',
        name: 'Договор поставки [Основной договор]',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '2012-08-23T00:00:00Z',
        isDeleted: false,
        isGoods: true,
      },
      {
        id: 16550,
        code: 'F0839626 ',
        name: 'Расхождения с поставщиком',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '0001-01-01T00:00:00Z',
        isDeleted: false,
        isGoods: true,
      },
      {
        id: 16964,
        code: 'F0840650 ',
        name: 'рекламные услуги',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '0001-01-01T00:00:00Z',
        isDeleted: false,
        isGoods: true,
      },
      {
        id: 25257,
        code: 'F0857942',
        name: 'Основной на РЕАЛИЗАЦИЮ',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '2012-08-23T00:00:00Z',
        isDeleted: false,
        isGoods: true,
      },
      {
        id: 25258,
        code: 'F0857943 ',
        name: 'Возвраты неотгруженные на РЕАЛИЗАЦИЮ',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '2012-08-23T00:00:00Z',
        isDeleted: false,
        isGoods: true,
      },
      {
        id: 31776,
        code: 'F0871189 ',
        name: 'Возврат отгруженный реализация',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '2012-08-23T00:00:00Z',
        isDeleted: false,
        isGoods: true,
      },
      {
        id: 35289,
        code: '0000-1096',
        name: 'ДС на ТП поставщику ООО Сталкер-Консалтинг (февраль)',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '0001-01-01T00:00:00Z',
        isDeleted: false,
        isGoods: false,
      },
      {
        id: 39126,
        code: '0000-6545',
        name: 'Дог на ок услуг июль Сталкер - консалтинг',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '2016-01-29T00:00:00Z',
        isDeleted: false,
        isGoods: false,
      },
      {
        id: 39786,
        code: '0000-7322',
        name: 'ДС БН о  20.01.16 Сталкер - консалтинг ООО',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '2012-08-23T00:00:00Z',
        isDeleted: false,
        isGoods: false,
      },
      {
        id: 42514,
        code: '0100-0755',
        name: 'Премия Покупателю компенсация декабрь Сталкер-Консалтинг ООО',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '2012-08-23T00:00:00Z',
        isDeleted: false,
        isGoods: false,
      },
      {
        id: 54056,
        code: '0300-9399',
        name: 'Договор Поставки № 23/08.02 от 23.08.2012',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '2012-08-23T00:00:00Z',
        isDeleted: false,
        isGoods: true,
      },
      {
        id: 88823,
        code: '1600-3422',
        name: 'Договор Продвижение товара №  от 21.08.2019',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '2019-08-21T00:00:00Z',
        isDeleted: false,
        isGoods: false,
      },
      {
        id: 89401,
        code: '1600-5849',
        name: 'Договор Реклама № 2608 от 26.08.2019',
        currencyID: 1,
        currencyName: 'руб',
        companyID: 1,
        companyName: 'Вайлдберриз ООО',
        date: '2019-08-26T00:00:00Z',
        isDeleted: false,
        isGoods: false,
      },
    ],
  },
  error: false,
  errorText: '',
  additionalErrors: {},
};
